name: 'Github-workflow-to-automate-AWS-resources'



# Controls when the workflow will run

on:

  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the "main" branch

  # push:

  #   branches: [ "main" ]

  # pull_request:

  #   branches: [ "main" ]



env:

  aws-region: us-east-1




# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  terraform:

    name: Terraform

    runs-on: ubuntu-latest

  # # This workflow contains a single job called "build"

  # build:

  #   # The type of runner that the job will run on

  #   runs-on: ubuntu-latest



    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: checkout

        uses: actions/checkout@v3

      - name: Terraform Hashicorp Setup

        uses: hashicorp/setup-terraform@v2

        with:

          terraform_version: 0.13.0

         

      - name: Configure AWS credentials from Test account

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}

          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}

          Aws-region: ${{env.aws-region}}



      # # Runs a single command using the runners shell

      # - name: Run a one-line script

      #   run: echo Hello, world!



      # # Runs a set of commands using the runners shell

      # - name: Run a multi-line script

      #   run: |

      #     echo Add other actions to build,

      #     echo test, and deploy your project.



      - name: terraform init  

        run: terraform init



      - name: terraform plan

        run: terraform plan



      - name: terraform apply

        run: terraform apply  -auto-approve 